#!/bin/sh /etc/rc.common

START=30
USE_PROCD=1

ARP_PROXY_BIN=/usr/sbin/arp-proxy

start_service()
{
	procd_open_instance
	procd_set_param command "$ARP_PROXY_BIN"
	procd_set_param respawn
	procd_close_instance

}

restart()
{
	stop "$@"
	sleep 1
	start "$@"
}
